# Streamlit secrets configuration
# Copy this to .streamlit/secrets.toml for local development

[default]
PAYPAL_CLIENT_ID = "your_paypal_client_id_here"
PAYPAL_SECRET = "your_paypal_secret_here"
PAYPAL_ENV = "sandbox"  # or "live" for production
OPENAI_API_KEY = "your_openai_api_key_here"